config/routes.rb
AuthenticationFromScratch::Application.routes.draw do
  get "static_pages/index"

  resources :users
  resources :sessions
  resources :password_resets
  root 'static_pages#index'
  get 'account_confirmation', to: 'users#account_confirmation'

end

app/models/user.rb
class User < ActiveRecord::Base

  has_secure_password

  before_save { self.email = email.downcase }
  before_create { generate_remember_token(:remember_token) }

  EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i

  validates :name, presence: true, length: { maximum: 100 }
  validates :email, presence: true, format: { with: EMAIL_REGEX },
  uniqueness: true, length: { minimum: 6 }
  validates :phone, presence: true, length: { maximum: 50 }
  validates :password, length: { minimum: 6 }

  def self.authenticate_user(email, password)
    user = find_by_email(email)
    if user && user.authenticate(password)
      user
    else
      nil
    end
  end

  def self.authenticate_user(email, password)
    user = find_by_email(email)
    if user && user.authenticate(password)
      user if user.email_confirmed
    end
  end

  def send_confirmation
    self.update_column(:password_reset_token, SecureRandom.urlsafe_base64)
    self.update_column(:password_sent_at, Time.zone.now)
    UserMailer.send_confirmation_mail(self).deliver
  end

  def generate_remember_token(column)
    begin
      self[column] = SecureRandom.urlsafe_base64
    end while User.exists?(column => self[column])
  end

  def send_password_reset
    self.update_column(:password_reset_token, SecureRandom.urlsafe_base64)
    self.update_column(:password_sent_at, Time.zone.now)
    UserMailer.send_password_reset_mail(self).deliver
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/password_resets_controller.rb
class PasswordResetsController < ApplicationController

  def create
    @user = User.find_by_email(params[:email])
    if @user
      @user.send_password_reset
      redirect_to root_path, notice: "Email has been sent with reset password instructions"
    else
      flash.now.alert = "This email is not registered with us."
      render 'new'
    end
  end
  
  def edit
    @user = User.find_by_password_reset_token!(params[:id])
  end
  
  def update
    @user = User.find_by_password_reset_token!(params[:id])
    if @user.password_sent_at < 2.hours.ago
      redirect_to new_users_password_reset_path, :alert => "Password reset has expired."
    elsif @user.update_attributes(edit_params)
      @user.update_attribute(:password_reset_token, nil)
      redirect_to new_session_url, :notice => "Password has been reset."
    else
      render "edit"
    end
  end
  
  private
  def edit_params
    params.require(:user).permit(:password, :password_confirmation)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  before_action :check_signed_in, except: :destroy

  def create
    user = User.authenticate_user(params[:email], params[:password])
    if user
      sign_in user if params[:remember_me]
      session_create user.id
      redirect_to root_url
    else
      flash.now.alert = "Invalid Email or Password"
      render 'new'
    end
  end

  def destroy
    sign_out
    session_destroy
    redirect_to root_url, notice: "Signed out successfully"
  end

  private
  def check_signed_in
    if signed_in?
      flash.now.alert = "Already signed in"
      redirect_to root_url
    end
  end

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController

  include SessionsHelper

  def index
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :check_signed_in, except: [:new, :create, :account_confirmation]

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      @user.send_confirmation
      redirect_to root_url, notice: "User Registered successfully"
    else
      render 'new'
    end
  end

  def update
    if @user.update_attributes(user_params)
      redirect_to root_url, notice: "User updated successfully"
    else
      render 'edit'
    end
  end

  def account_confirmation
    @user = User.find_by_password_reset_token(params[:token])
    if(@user)
      @user.update_column(:email_confirmed, true)
      @user.update_column(:password_reset_token, nil)
      redirect_to new_session_url, :notice => "Account confirmed"
    else
      redirect_to new_session_url, :notice => "Account could not be confirmed"
    end
  end

  private
  def user_params
    params.require(:user).permit(:name,:email,:phone,:password,:password_confirmation)
  end

  def check_signed_in
    if !signed_in?
      flash.alert.now = "Please sign in to continue"
      redirect_to root_url
    else
      @user = current_user
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/password_resets_helper.rb
module PasswordResetsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

  def current_user=(user)
    @current_user = user
  end

  def current_user
    if session[:user]
      @current_user ||= User.find(session[:user])
    elsif cookies[:remember_token]
      @current_user ||= User.find_by_remember_token!(cookies[:remember_token])
    end
  end

  def signed_in?
    !current_user.nil?
  end

  def sign_in(user)
    cookies.permanent[:remember_token] = user.remember_token
    self.current_user = user
  end

  def sign_out
    self.current_user = nil
    cookies.delete(:remember_token)
  end

  def session_create(user_id)
    session[:user] = user_id
  end

  def session_destroy
    session[:user] = nil
  end

end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AuthenticationFromScratch</title>
    <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <%= render partial: "partials/header" %>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/partials/_header.html.erb
<nav class="navbar navbar-default" role="navigation">
  <div class="container">
    <%= link_to "Simple Authentication", root_url, class: "navbar-brand" %>
    <ul class="nav navbar-nav navbar-right">
      <% if signed_in? %>
        <li><%= link_to "Logout", session_path(current_user), method: :delete %></li>
      <% else %>
        <li><%= link_to "Register", new_user_path %></li>
      <% end %>
    </ul>
  </div>
</nav>

app/views/partials/_login.html.erb
<div class="row">
  <div class="col-lg-6 col-lg-offset-3">
    <div class="well">
      <h4>Login</h4><hr>
      <%= form_tag sessions_path do %>
        <div class="form-group">
          <%= label_tag :email %>
          <%= text_field_tag :email, params[:email], class: "form-control", :placeholder => "Email address" %>
        </div>
        <div class="form-group">
          <%= label_tag :password %>
          <%= password_field_tag :password, nil, class: "form-control", :placeholder => "Password" %>
        </div>
        <div class="checkbox">
          <%= label_tag :remember_me ,:class => "checkbox vsmall" do %>
            <%= check_box_tag :remember_me, 1, params[:remember_me] %>
            Remember me
          <% end %>
        </div>
        <div class="actions">
          <%= submit_tag :sign_in, class: "btn btn-default", :value => "Sign in" %>
        </div>
        <br>
        <div class="messages">
          <% flash.each do |name,msg| %>
            <% if name.to_s == "notice" %>
              <div class="alert alert-success alert-dismissable">
                <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
                <span><%= msg %></span>
              </div>
            <% else %>
              <div class="alert alert-danger alert-dismissable">
                <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
                <span><%= msg %></span>
              </div>
            <% end %>
          <% end %>
        </div>
      <% end %>
      <%= link_to 'Forgot Password', new_password_reset_path %>
    </div>
  </div>
</div>

app/views/password_resets/edit.html.erb
<div class="row">
  <div class="col-lg-6 col-lg-offset-3">
    <div class="well">
      <h4>Enter new password</h4><hr>
      <%= form_for @user, url: password_reset_path(params[:id]) do |f| %>
        <div class="form-group">
          <%= f.label :password %>
          <%= f.password_field :password, placeholder: "Repeat password", class: "form-control" %>
        </div>
        <div class="form-group">
          <%= f.label :password_confirmation %>
          <%= f.password_field :password_confirmation, placeholder: "Repeat password", class: "form-control" %>
        </div>
        <div class="actions">
          <%= f.submit "Update Password", class: "btn btn-primary" %>
        </div>
        <br>
        <div class="messages">
          <% if @user.errors.any? %>
            <% for message in @user.errors.full_messages %>
              <div class="alert alert-danger">
                <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
                <%= message %>
              </div>
            <% end %>
          <% end %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/password_resets/new.html.erb
<div class="row">
  <div class="col-lg-6 col-lg-offset-3">
    <div class="well">
      <h4>Forgot Password </h4><hr>
      <%= form_tag password_resets_path do %>
        <div class="form-group">
          <%= label_tag :email %>
          <%= text_field_tag :email, params[:email], :placeholder => "Email address", class: "form-control" %>
        </div>
        <div class="actions">
          <%= submit_tag :recover, value: "Recover", class: "btn btn-primary" %>
        </div>
        <br>
        <div class="messages">
          <% flash.each do |name,msg| %>
            <div class="alert alert-danger">
              <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
              <%= msg %>
            </div>
          <% end %>
        </div>
      <% end %> 
    </div>
  </div>
</div>

app/views/static_pages/index.html.erb
<div class="row">
  <% if signed_in? %>
    <div class="jumbotron">
      <h2>Hello, <%= current_user.name %>!</h2><br>
      <h5>Find the complete source code on <%= link_to "Github", "https://github.com/Just-hack/authentication-from-scratch", target: "_blank" %>
    </div>
  <% else %>
    <%= render 'partials/login' %><br>
  <% end %>    
</div>

app/views/users/new.html.erb
<div class="row">
  <div class="col-lg-6 col-lg-offset-3">
    <div class="well">
      <h4>Register</h4><hr>
        <% if @user.errors.any? %>
          <div class="alert alert-danger">
            <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
            <% @user.errors.full_messages.each do |msg| %>
              <%= msg %><br>
            <% end %>
          </div>
        <% end %>
      <%= form_for :user, url: users_path do |f| %>
        <div class="form-group">
          <%= f.label :name %>
          <%= f.text_field :name, class: "form-control", placeholder: "Name" %>
        </div>
        <div class="form-group">
          <%= f.label :email %>
          <%= f.text_field :email, class: "form-control", placeholder: "Email" %>
        </div>
        <div class="form-group">
          <%= f.label :phone %>
          <%= f.text_field :phone, class: "form-control", placeholder: "Phone number" %>
        </div>
        <div class="form-group">
          <%= f.label :password %>
          <%= f.password_field :password, class: "form-control", placeholder: "Password" %>
        </div>
        <div class="form-group">
          <%= f.label :repeat_password %>
          <%= f.password_field :password_confirmation, class: "form-control", placeholder: "Repeat Password" %>
        </div>
        <div class="actions">
          <%= f.submit :create_account, class: "btn btn-primary", value: "Create Account" %>
        </div>
      <% end %>
    </div>
  </div>
</div>